//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITB.CMS_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints_SubType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Complaint_Type_Id { get; set; }
        public Nullable<double> Retaining_Hours { get; set; }
        public string Url { get; set; }
        public string Color_Code { get; set; }
        public string Url_Urdu { get; set; }
        public string Ideal_Action { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Origin_Id { get; set; }
        public string TagId { get; set; }
    }
}
